-- Clear everything
DROP DATABASE IF EXISTS chime;

-- Create database + switch to it
CREATE DATABASE chime
	CHARACTER SET utf8mb4 
	COLLATE utf8mb4_unicode_ci;

USE chime;

-- Users
CREATE TABLE users
(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(256) NOT NULL,
	password TEXT NOT NULL,
	verified TINYINT(1) NOT NULL DEFAULT 0,
	suspended TINYINT(1) NOT NULL DEFAULT 0,
	bio TEXT(200),
	website VARCHAR(256), 
	location VARCHAR(32),
	color VARCHAR(6),
	two_factor_enabled VARCHAR(32),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

-- App Tokens
-- Access Levels: (1) Read (2) Read/Write (3) Read/Write/Account
CREATE TABLE tokens
(
	id VARCHAR(128) NOT NULL,
	token VARCHAR(32) NOT NULL,
	user_id INT NOT NULL,
	description TEXT(256),
	access_level INT(1) NOT NULL DEFAULT 1,
    created_ip VARCHAR(32),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

-- Posts
CREATE TABLE posts
(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	body VARCHAR(200),
	mentions VARCHAR(200),
	hashtags VARCHAR(200),
	urls VARCHAR(200),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

-- Comments
CREATE TABLE comments
(
	id INT NOT NULL AUTO_INCREMENT,
	post_id INT NOT NULL,
	user_id INT NOT NULL,
	body VARCHAR(200),
	mentions VARCHAR(200),
	hashtags VARCHAR(200),
	urls VARCHAR(200),	
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

-- Follows
CREATE TABLE follows
(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT,
	follow_id INT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

-- Likes
CREATE TABLE likes
(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	likeable_id INT NOT NULL,
	likeable_type VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;
